version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU
skip_tags: true

init:
  - cmd: tzutil /s "Tokyo Standard Time"
build_script:
  - ps: >-
      Get-ChildItem **\*.sln | % -ErrorAction Stop { nuget restore $_; msbuild $_ /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" }
after_build:
  - ps: >-
      $outdir = "artifacts"

      $archivedir = "archives"

      New-Item -ItemType Directory $outdir

      New-Item -ItemType Directory $archivedir

      Get-ChildItem *.sln -Recurse | % {

          $name = Split-Path $_ -Parent | Split-Path -Leaf

          $srcdir = Split-Path $_ -Parent

          $destdir = Join-Path $outdir $name

          New-Item -ItemType Directory $destdir

          Get-ChildItem -Recurse "$srcdir\**\bin\$configuration\*.dll" | Copy-Item -Destination $destdir

          & {

              $readme = Join-Path $destdir "readme.txt"

              Get-Content "$srcdir\readme.txt" >> $readme

              Get-Content distribution-readme-footer.txt >> $readme

              Get-Date -Format "yyyy/MM/dd" >> $readme

          }

          Remove-Item -ErrorAction SilentlyContinue "$destdir\PmdEPlugin.dll"

          Remove-Item -ErrorAction SilentlyContinue  "$destdir\PmxEPlugin.dll"

          Remove-Item -ErrorAction SilentlyContinue  "$destdir\SlimDX.dll"

          & {

              Push-Location $outdir

              7z a "$archivedir\$name.zip" $name

              Pop-Location

          }

      }
artifacts:
  - path: archives
    name: PEPlugins
deploy:
  - provider: GitHub
    tag: build-$(appveyor_build_version)
    release: PmXEditorPlugins Build $(appveyor_build_version)
    auth_token:
      secure: KkbkUfg5iFaqdqxRAHRvPZv5+nfF99DyufxN6IijxL2TWoV3QTdkAkrnyNvIPt9+
    artifact: PmXEditorPlugins
    draft: true
    on:
      branch: master
