version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU
skip_tags: true

init:
  - cmd: tzutil /s "Tokyo Standard Time"
build_script:
  - ps: >-
      Get-ChildItem **\*.sln | % { nuget restore $_; msbuild $_ /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" }
after_build:
  - ps: >-
      $artifacts = "PmXEditorPlugins"

      New-Item -type directory $artifacts

      "$artifacts Build $env:APPVEYOR_BUILD_VERSION" > $artifacts\readme.txt

      Get-Content distribution-readme.txt >> $artifacts\readme.txt

      Get-Date -Format "yyyy/MM/dd" >> $artifacts\readme.txt

      Get-ChildItem **\*.dll -Recurse | Copy-Item -force -destination $artifacts

      & { Remove-Item $artifacts\PmdEPlugin.dll }

      & { Remove-Item $artifacts\PmxEPlugin.dll }

      & { Remove-Item $artifacts\SlimDX.dll }

artifacts:
  - path: PmXEditorPlugins
    name: PmXEditorPlugins
deploy:
  - provider: GitHub
    tag: build-$(appveyor_build_version)
    release: PmXEditorPlugins Build $(appveyor_build_version)
    auth_token:
      secure: KkbkUfg5iFaqdqxRAHRvPZv5+nfF99DyufxN6IijxL2TWoV3QTdkAkrnyNvIPt9+
    artifact: PmXEditorPlugins
    draft: true
    on:
      branch: master
